name: mysql

on:
  pull_request:
    paths: &paths
      - 'migrations/**'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/mysql.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php }}-mysql-${{ matrix.mysql }}

    env:
      extensions: pdo, pdo_mysql

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 8.1

        mysql:
          - 5.7
          - latest

    services:
      mysql:
        image: mysql:${{ matrix.mysql }} # zizmor: ignore[unpinned-images]
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: ''
          MYSQL_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run tests with phpunit
        run: vendor/bin/phpunit --testsuite Mysql --coverage-clover=coverage.xml --colors=always

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
